# Generated by Django 2.0 on 2019-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
        migrations.AddField(
            model_name='openid',
            name='islogin',
            field=models.CharField(default='no', max_length=10, verbose_name='登录状态'),
        ),
        migrations.AlterField(
            model_name='openid',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
