# Generated by Django 2.0 on 2019-04-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190331_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'verbose_name': '视频观看进度', 'verbose_name_plural': '视频观看进度'},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name': '学生成绩', 'verbose_name_plural': '学生成绩'},
        ),
        migrations.AlterField(
            model_name='course',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='editdate',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='createdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加时间'),
        ),
    ]
